version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: noctis_db
    environment:
      POSTGRES_DB: noctis
      POSTGRES_USER: noctis
      POSTGRES_PASSWORD: noctis
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # for local dev access
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U noctis -d noctis"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: noctis_redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379" # for local dev access
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: noctis_api
    # Load secrets and configs; ensure a .env file exists at repo root
    env_file:
      - .env
    environment:
      # Override DB/Redis hosts to internal service names
      DATABASE_URL: postgresql+asyncpg://noctis:noctis@db:5432/noctis
      REDIS_URL: redis://redis:6379/0
      # Optionally define TURN in .env (uncomment to force here)
      # TURN_SERVER_URL: ${TURN_SERVER_URL}
      # TURN_USERNAME: ${TURN_USERNAME}
      # TURN_PASSWORD: ${TURN_PASSWORD}
      # Tight CORS for production; leave to .env by default
      # CORS_ORIGINS: '["https://noctisapp.com","https://app.noctisapp.com"]'
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    restart: unless-stopped
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --workers 4

  # Optional: coturn TURN server (enable if you need a self-hosted relay for WebRTC)
  # turn:
  #   image: instrumentisto/coturn
  #   container_name: noctis_turn
  #   network_mode: "host" # or expose ports below if not using host networking
  #   environment:
  #     - TURN_USERNAME=${TURN_USERNAME}
  #     - TURN_PASSWORD=${TURN_PASSWORD}
  #   command: >
  #     --no-cli
  #     --no-tls
  #     --no-dtls
  #     --fingerprint
  #     --lt-cred-mech
  #     --use-auth-secret
  #     --static-auth-secret=${TURN_PASSWORD}
  #     --realm=${TURN_REALM:-noctis.local}
  #     --listening-port=3478
  #     --min-port=49160
  #     --max-port=49200
  #   ports:
  #     - "3478:3478/udp"
  #     - "3478:3478/tcp"
  #     - "49160-49200:49160-49200/udp"
  #   restart: unless-stopped

volumes:
  db_data:
  redis_data:
